from adjacent_chunker import AdjacentChunker

s = "Python is widely used for scripting and automation. It has a large standard library for handling common tasks. You can use Python to analyze data with libraries like Pandas. Web frameworks like Django and Flask make building websites easier. Python is often used in scientific computing and research. It supports object-oriented, functional, and procedural programming. Python's readability makes it a good choice for beginners. You can create visualizations using libraries like Matplotlib. Python is cross-platform and works on Windows, macOS, and Linux. It integrates well with other languages like C and Java."
diverse = "The quick brown fox jumps over the lazy dog, while the sun sets in a kaleidoscope of colors. Quantum mechanics, though perplexing, governs the behavior of particles at the smallest scales. Meanwhile, ancient civilizations like the Egyptians built pyramids that still stand as marvels of engineering. In the bustling city, a barista crafts a latte with intricate foam art, while a street musician plays a soulful melody on his saxophone. The internet, a vast network of interconnected devices, has revolutionized communication, commerce, and entertainment. Meanwhile, in the depths of the ocean, bioluminescent creatures illuminate the dark waters, creating an otherworldly spectacle. Climate change, driven by human activities, poses a significant threat to ecosystems worldwide, urging the need for sustainable practices. As artificial intelligence advances, ethical considerations around its use become increasingly important. The aroma of freshly baked bread wafts through the air, evoking memories of childhood and simpler times. In the realm of literature, authors like Shakespeare and Toni Morrison have left indelible marks on the world, exploring themes of love, identity, and human nature. The periodic table, a cornerstone of chemistry, organizes elements based on their atomic structure, revealing patterns that underpin the material world. Meanwhile, in the cosmos, black holes warp spacetime, and galaxies collide in a dance that spans billions of years. The human brain, with its billions of neurons, remains one of the most complex and least understood organs, capable of creativity, emotion, and profound thought. As technology evolves, so too does the way we interact with the world, blending the physical and digital realms in unprecedented ways."
focused = "The history of artificial intelligence dates back to ancient times, when myths and stories spoke of artificial beings endowed with intelligence by their creators. In the 20th century, the field of AI began to take shape with the development of early computers and the pioneering work of Alan Turing, who proposed the idea of a machine capable of simulating human intelligence. The 1956 Dartmouth Conference is often considered the birth of AI as a formal discipline, where researchers gathered to explore the potential of machines to mimic human thought. Over the decades, AI has evolved significantly, with breakthroughs in machine learning, natural language processing, and computer vision. Today, AI powers a wide range of applications, from virtual assistants like Siri and Alexa to self-driving cars and advanced medical diagnostics. Despite its rapid progress, AI still faces challenges, such as ensuring ethical use, addressing biases in algorithms, and achieving general intelligence. Researchers continue to push the boundaries of what AI can do, exploring areas like reinforcement learning, neural networks, and quantum computing. As AI becomes more integrated into society, it raises important questions about the future of work, privacy, and human-machine interaction. The potential of AI to transform industries and improve lives is immense, but it also requires careful consideration of its societal impact. By fostering collaboration between technologists, policymakers, and ethicists, we can ensure that AI is developed and deployed in ways that benefit humanity as a whole."
text_people = "Alice stepped forward and spoke confidently, 'We need to act now if we want to prevent the situation from escalating.' She glanced around the room, her determination evident in her sharp gaze. Bob leaned back in his chair, arms crossed, and replied, 'Act now? We barely have enough information to make an informed decision. Rushing in could make things worse.' His tone was cautious but firm. Carol, seated at the end of the table, raised her hand to interject, 'I think Alice has a point. Waiting too long might close the window of opportunity. But perhaps we can gather more data while preparing to act.' Her suggestion struck a balance between urgency and caution. David, who had been silent until now, finally spoke up, 'We all bring valid concerns, but let’s not forget the stakes. Whatever we do, we need to be united in our approach.' His words carried a tone of gravity, bringing the group’s scattered ideas back into focus."
text_more_people = "Alice stepped forward and spoke confidently, 'We need to act now if we want to prevent the situation from escalating. Delaying any longer could be disastrous, and I believe we already have enough evidence to justify taking the first step.' She glanced around the room, her determination evident in her sharp gaze as she waited for a response. Bob leaned back in his chair, arms crossed, and replied, 'Act now? We barely have enough information to make an informed decision. Rushing in could make things worse, not better.' His tone was cautious but firm, and his expression suggested a deep skepticism. Carol, seated at the end of the table, raised her hand to interject, 'I think Alice has a point. Waiting too long might close the window of opportunity. But perhaps we can gather more data while preparing to act.' Her suggestion struck a balance between urgency and caution, attempting to bridge the gap between Alice and Bob. David, who had been silent until now, finally spoke up, 'We all bring valid concerns, but let’s not forget the stakes. Whatever we do, we need to be united in our approach. A divided strategy will only weaken our position.' His words carried a tone of gravity, bringing the group’s scattered ideas back into focus, and the room fell silent as everyone considered his point."

if __name__ == '__main__':
    adjacent_chunker = AdjacentChunker(1, 3, .35, .45, 2)
    chunks = adjacent_chunker.chunk_adjacent(text_more_people)
    del adjacent_chunker
    
    for chunk in chunks:
        print('Evaluate the Semantic Split')
        print(chunk + '\n')

